### ISSUE TITLE
Investigate REST server

### ISSUE THREAD

**Issue by denyskulykov** [stasya72008/highway-to-hell#1]
Need to find several popular solutions and compare with each other.

**Comment by stasya72008** [comment]
Flask
-	RESTful request dispatching (Request Context)
-	Easy to start with
-	Small

Django
-	High-level
-	Fast and secure
-	For large projects

CherryPy
-	Multiple HTTP servers support
-	Object-oriented
-	Modular

Web.py
-	Good for small projects
-	Simple
-	Not actively maintained	

Eve
-	Based on Flask
-	Allows to build and deploy highly customizable, fully featured RESTful Web Services
-	Native support for MongoDB. Also extensions for SQL, Elasticsearch and Neo4js backends are provided

No framework (Python standard library)
-	So-so :P
