### ISSUE TITLE
[Env] Config database

### ISSUE THREAD

**Issue by denyskulykov** [stasya72008/highway-to-hell#18]
https://store.docker.com/images/postgres
https://store.docker.com/images/mysql

Up container
Please, use port (5000-5005) to show datebase outside  

Create users
you can use default locally, but Don't use default user for outside.

Check to allow to see database from you workstation

**Comment by stasya72008** [comment]
Command:
docker run --detach --name=<container_name> --env="MYSQL_ROOT_PASSWORD=<password>" --publish <ext_port>:3306 hypriot/rpi-mysql
