### ISSUE TITLE
Implement REST server

### ISSUE THREAD

**Issue by denyskulykov** [stasya72008/highway-to-hell#2]
Need to create template of rest server with APIv1 

Methods, for example:
get_users() return json with users
add_user()
delete_user()
get_tasks_of_users() return json with task
add_task()
delete_task()
set_task_action() 

Naming of REST Request:
http://www.restapitutorial.com/lessons/restfulresourcenaming.html

**Comment by stasya72008** [comment]
(dancing penguin)
