### ISSUE TITLE
Investigate the Python SQL toolkit (SQL providers) 

### ISSUE THREAD

**Issue by denyskulykov** [stasya72008/highway-to-hell#5]
This task is the same like #1

**Comment by stasya72008** [comment]
SQLAlchemy
•	The most popular database toolkit
•	Supports various databases
•	Using ORM is optional

SQLObject
•	Similar to Ruby on Rails' ActiveRecord
•	Suports MySQL, PostgreSQL, SQLite, Sybase SQL Server, MaxDB, Microsoft SQL Server and Firebird.
•	Only Python 2

Storm
•	allows developers to construct complex queries across multiple database tables to support dynamic storage and retrieval of object information
•	Native support for MySQL, PostgreSQL and SQLite, API for others
